# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deployDoc
  script:
    - mkdir .public
    - cp -r docs/ .public
    - cp -r index.html .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
